config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'menu', to: 'static_pages#menu'
  resources :questions, only: %i[index create] do
    collection do
      get 'result'
    end
  end
  resources :users, only: [:show]
  resources :goals, only: %i[show new create update edit index] do
    post :record, on: :member
    get :check_record, on: :member
  end
  resources :diaries

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/diary.rb
# frozen_string_literal: true

# Diary represents a daily log of the user's physical and mental condition.
# It includes attributes for body temperature, weight, body fat, physical condition, and mental condition.
# Each diary entry is associated with a user and records the user's health metrics and conditions for the day.

class Diary < ApplicationRecord
  belongs_to :user

  validates :start_time, presence: true
  validates :body_temperature, :weight, :body_fat, numericality: true, allow_nil: true
  validates :physical_condition, inclusion: { in: %w[physical_bad physical_normal physical_good] }, allow_nil: true
  validates :mental_condition, inclusion: { in: %w[mental_bad mental_normal mental_good] }, allow_nil: true

  enum physical_condition: { physical_bad: 0, physical_normal: 1, physical_good: 2 }, _prefix: true
  enum mental_condition: { mental_bad: 0, mental_normal: 1, mental_good: 2 }, _prefix: true
end

app/controllers/diaries_controller.rb
# frozen_string_literal: true

# DiariesController handles actions related to the Diary model.
# It allows users to create, update, show, and delete diary entries.
# Additionally, it manages the recording of physical and mental conditions.

class DiariesController < ApplicationController
  before_action :set_diary, only: %i[show edit update destroy]

  def index
    @diaries = user_diaries
    @today_diary = current_user.diaries.find_by(start_time: Time.zone.today)
  end

  def show; end

  def new
    if current_user.diaries.exists?(start_time: Time.zone.today)
      redirect_to diaries_path, alert: t('.alert')
    else
      @diary = Diary.new
    end
  end

  def edit; end

  def create
    if current_user.diaries.exists?(start_time: Time.zone.today)
      redirect_to diaries_path, alert: t('.alert')
    else
      @diary = current_user.diaries.new(diary_params)
      if @diary.save
        redirect_to @diary, success: t('.success')
      else
        flash.now[:danger] = t('.failure')
        render :new, status: :unprocessable_entity
      end
    end
  end

  def update
    if @diary.update(diary_params)
      redirect_to @diary, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @diary.destroy
      redirect_to diaries_url, success: t('.success')
    else
      redirect_to diaries_url, failure: t('.failure')
    end
  end

  private

  def set_diary
    @diary = Diary.find(params[:id])
    Rails.logger.debug { "Set Diary for ID: #{@diary.id}" }
  end

  def user_diaries
    current_user.diaries.order(:start_time)
  end

  def diary_params
    params.require(:diary).permit(:start_time, :body_temperature, :weight, :body_fat, :physical_condition,
                                  :mental_condition)
  end
end

app/views/diaries/_form.html.erb
<%= form_with model: @diary, local: true do |form| %>
  <div>
    <%= form.hidden_field :start_time, value: Date.today %>
  </div>
  <div>
    <%= form.label :body_temperature, "体温 (°C)" %>
    <%= form.number_field :body_temperature, step: 0.1 %><br><br>
  </div>
  <div>
    <%= form.label :weight, "体重 (Kg)" %>
    <%= form.number_field :weight, step: 0.1 %><br><br>
  </div>
  <div>
    <%= form.label :body_fat, "体脂肪 (%)" %>
    <%= form.number_field :body_fat, step: 0.1 %><br><br>
  </div>
  <div>
    <%= form.label :physical_condition, "体調" %>
    <div class="physical-condition-options">
      <%= form.radio_button :physical_condition, 'physical_bad', id: 'physical_condition_bad', class: 'btn-check d-none', autocomplete: 'off' %>
      <%= label_tag 'physical_condition_bad', class: 'physical-icon' do %>
        <i class="fa fa-frown-o" aria-hidden="true"></i>
      <% end %>

      <%= form.radio_button :physical_condition, 'physical_normal', id: 'physical_condition_normal', class: 'btn-check d-none', autocomplete: 'off' %>
      <%= label_tag 'physical_condition_normal', class: 'physical-icon' do %>
        <i class="fa fa-meh-o" aria-hidden="true" ></i>
      <% end %>

      <%= form.radio_button :physical_condition, 'physical_good', id: 'physical_condition_good', class: 'btn-check d-none', autocomplete: 'off' %>
      <%= label_tag 'physical_condition_good', class: 'physical-icon' do %>
        <i class="fa fa-smile-o" aria-hidden="true" ></i>
      <% end %>
    </div>
  </div>
  <div>
    <%= form.label :mental_condition, "メンタル" %>
    <div class="mental-condition-options">
      <%= form.radio_button :mental_condition, 'mental_bad', id: 'mental_condition_bad', class: 'btn-check d-none', autocomplete: 'off' %>
      <%= label_tag 'mental_condition_bad', class: 'mental-icon' do %>
        <i class="fa fa-frown-o" aria-hidden="true" ></i>
      <% end %>

      <%= form.radio_button :mental_condition, 'mental_normal', id: 'mental_condition_normal', class: 'btn-check d-none', autocomplete: 'off' %>
      <%= label_tag 'mental_condition_normal', class: 'mental-icon' do %>
        <i class="fa fa-meh-o" aria-hidden="true" ></i>
      <% end %>

      <%= form.radio_button :mental_condition, 'mental_good', id: 'mental_condition_good', class: 'btn-check d-none', autocomplete: 'off' %>
      <%= label_tag 'mental_condition_good', class: 'mental-icon' do %>
        <i class="fa fa-smile-o" aria-hidden="true" ></i>
      <% end %>
    </div>
  </div>
  <div>
    <%= form.submit "登録", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="top-wrapper">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1>編集</h1>
      <div class="box">
        <div class="white-box center">
          <%= render 'form', diary: @diary %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/diaries/index.html.erb
<% content_for(:title, t('.title'))%>
<div class="container">
  <div class="top-wrapper">
    <div class="col-md-10 col-lg-8 mx-auto">
      <div class="box">
        <div class="white-box">
          <%= month_calendar events: @diaries do |date, records| %>
            <%= date.day %>

            <% if records.present? %>
              <% records.each do |record| %>
                <div>
                  <%= link_to diary_path(record) do %>
                    <% if record.physical_condition.present? %>
                      <i class="fa fa-<%= record.physical_condition == 'physical_bad' ? 'frown-o' : record.physical_condition == 'physical_normal' ? 'meh-o' : 'smile-o' %>" aria-hidden="true" style="font-size: 17px;"></i>
                    <% end %>
                    <% if record.mental_condition.present? %>
                      <i class="fa fa-<%= record.mental_condition == 'mental_bad' ? 'frown-o' : record.mental_condition == 'mental_normal' ? 'meh-o' : 'smile-o' %>" aria-hidden="true" style="font-size: 17px;"></i>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>

          <% end %>
          <% unless @today_diary %>
            <%= link_to new_diary_path, class: 'btn btn-primary' do %>
              <i class="fa fa-plus-circle" aria-hidden="true" style="font-size: 20px;"></i> 今日の記録を作成
            <% end %>
          <% else %>
            <p>本日の記録は既に作成されています。</p>
          <% end %>
        </div>
      </div>
      <div class="box">
        <div class="white-box">
          <div class="container my-4">
            <%= line_chart [
                            {name: "体温", data: @diaries.map { |diary| [diary.start_time.strftime("%Y-%m-%d"), diary.body_temperature] }},
                            {name: "体重", data: @diaries.map { |diary| [diary.start_time.strftime("%Y-%m-%d"), diary.weight] }},
                            {name: "体脂肪", data: @diaries.map { |diary| [diary.start_time.strftime("%Y-%m-%d"), diary.body_fat] }}
                          ] %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/diaries/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="top-wrapper">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1>新規作成</h1>
      <div class="box">
        <div class="white-box center">
          <%= render 'form', diary: @diary %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/diaries/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="top-wrapper">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1>記録詳細</h1>
      <div class="box">
        <div class="white-box center">
          <p>日付: <%= @diary.start_time.strftime("%b %d") %></p>
          <p>体温 (°C): <%= @diary.body_temperature %></p>
          <p>体重 (Kg): <%= @diary.weight %></p>
          <p>体脂肪 (%): <%= @diary.body_fat %></p>
          <p>体調: <%= t("activerecord.attributes.diary.physical_condition.#{@diary.physical_condition}") %></p>
          <p>メンタル: <%= t("activerecord.attributes.diary.mental_condition.#{@diary.mental_condition}") %></p>
          <div class="row justify-content-center align-items-center">
            <div class="col-auto">
              <%= button_to '削除', diary_path(@diary), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-diary-delete' %>
              <%= link_to '編集', edit_diary_path(@diary), class: 'btn btn-diary-edit' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>