config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'menu', to: 'static_pages#menu'
  resources :questions, only: %i[index create] do
    collection do
      get 'result'
    end
  end
  resources :users, only: [:show]
  resources :goals, only: %i[show new create update edit index] do
    post :record, on: :member
    get :check_record, on: :member
  end
  resources :diaries

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_auth_buttons.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <%- resource_class.omniauth_providers.each do |provider| %>
        <%= button_to omniauth_authorize_path(resource_name, provider), data: { turbo: false }, class: 'transparent-button', id: "#{provider}_login" do %>
          <%= image_tag 'login.png' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation'>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item'>
          <%= link_to 'トップ', root_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to '冷え性診断', questions_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12 text-center'>
        <div class='header-main'>
          <%= link_to "利用規約", terms_path, class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover", target: "_blank" %>
          <%= link_to "プライバシーポリシー", privacy_path, class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
          <%= link_to "問い合わせ", "https://forms.gle/LFipEJM96NG52B71A", class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
        </div>
        <div class='copyright'>
          <p>© 2024 - Present HieMiru. All rights reserved.</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation'>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item d-flex align-items-center'><i class="fa-regular fa-snowflake"></i>
          <%= link_to '冷え性診断', questions_path, class: 'nav-link' %>
        </li>
        <li class='nav-item d-flex align-items-center'><i class="fa-regular fa-circle"></i>
          <% if current_user.goals.present? && current_user.goals.first.persisted? %>
            <% Rails.logger.debug "Goals: #{current_user.goals.to_a.inspect}" %>
            <%= link_to '記録', goal_path(current_user.goals.first), class: 'nav-link' %>
          <% else %>
            <%= link_to '記録', new_goal_path, class: 'nav-link' %>
          <% end %>
        </li>
        <li class='nav-item d-flex align-items-center'><i class="fa-solid fa-chart-pie"></i>
          <%= link_to '分析', diaries_path, class: 'nav-link' %>
        </li>
        <li class='nav-item d-flex align-items-center'><i class="fa-solid fa-bars"></i>
          <%= link_to 'メニュー', menu_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

<!-- Tabbar for smaller screens -->
<header>
  <div class="tabbar">
    <ul class='navbar-nav main-nav nav-pills nav-justified'>
      <li class='nav-item'><i class="fa-regular fa-snowflake"></i>
        <%= link_to '冷え性診断', questions_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'><i class="fa-regular fa-circle"></i>
        <% if current_user.goals.present? && current_user.goals.first.persisted? %>
          <%= link_to '記録', goal_path(current_user.goals.first), class: 'nav-link' %>
        <% else %>
          <%= link_to '記録', new_goal_path, class: 'nav-link' %>
        <% end %>
      </li>
      <li class='nav-item'><i class="fa-solid fa-chart-pie"></i>
        <%= link_to '分析', diaries_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'><i class="fa-solid fa-bars"></i>
        <%= link_to 'メニュー', menu_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</header>