config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'menu', to: 'static_pages#menu'
  resources :questions, only: %i[index create] do
    collection do
      get 'result'
    end
  end
  resources :users, only: [:show]
  resources :goals, only: %i[show new create update edit index] do
    post :record, on: :member
    get :check_record, on: :member
  end
  resources :diaries

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/goal.rb
# frozen_string_literal: true

# Goal represents a user's goal related to improving or managing their cold sensitivity.
# Each goal is associated with a user and can have various attributes like the goal body,
# the count of achievements, the last recorded date, and an optional association to a cold symptom.

class Goal < ApplicationRecord
  belongs_to :user
  belongs_to :cold_symptom

  validates :goal_body, presence: true
  validates :count, presence: true
end

app/controllers/goals_controller.rb
# frozen_string_literal: true

# GoalsController handles actions related to the Goal model.
# It allows users to create, update, show, and delete goals.
# Additionally, it manages the recording of goal achievements.

class GoalsController < ApplicationController
  before_action :set_goal, only: %i[show edit update check_record record]

  def show; end

  def new
    @goal = current_user.goals.build
    @cold_symptom = current_user.cold_symptoms.first
  end

  def edit
    @cold_symptom = current_user.cold_symptoms.first
  end

  def create
    @goal = current_user.goals.build(goal_params)
    @goal.cold_symptom_id ||= ColdSymptom.first&.id
    @cold_symptom = current_user.cold_symptoms.first

    if @goal.save
      redirect_to @goal, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def check_record
    @goal.last_recorded_at && @goal.last_recorded_at >= Time.zone.now.beginning_of_day
    redirect_to @goal, success: t('goals.update.success')
    render :show, status: :unprocessable_entity
  end

  def record
    if already_recorded_today?
      render json: { error: 'You can only record once per day.' }, status: :forbidden
      return
    end
    @goal.update(count: @goal.count + 1, last_recorded_at: Time.zone.now)
    reset_goal_count if @goal.count > 7
    respond_to_goal_save
  end

  def update
    @cold_symptom = current_user.cold_symptoms.first
    if @goal.update(goal_params)
      redirect_to @goal, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_goal
    @goal = current_user.goals.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:goal_body, :cold_symptom_id, :count)
  end

  def already_recorded_today?
    @goal.last_recorded_at && @goal.last_recorded_at >= Time.zone.now.beginning_of_day
  end

  def reset_goal_count
    @goal.update!(count: 0)
  end

  def respond_to_goal_save
    if @goal.save
      respond_to do |format|
        format.json { render json: { count: @goal.count } }
      end
    else
      respond_to do |format|
        format.json { render json: { error: 'Failed to record goal' }, status: :unprocessable_entity }
      end
    end
  end
end

app/views/goals/_form.html.erb
<div class="box">
  <div class="white-box center">
    <%= form_with model: @goal, local: true do |f| %>
      <%= f.label :goal_body do %>
        冷え性を改善するための目標を設定しましょう！<br>
        まずは７日間目標を継続
      <% end %>
      <%= f.text_area :goal_body, class: "form-control mb-3", row: "4", placeholder: current_user.cold_symptoms.first %>

      <% if current_user.cold_symptoms.present? %>
        <%= f.hidden_field :cold_symptom_id, value: @cold_symptom.id %>
        <%= "あなたは、#{@cold_symptom.localized_symptom_type}なので、" %><br>
        <%= @cold_symptom.solution %><br>
        <%= "の目標設定がおすすめです！" %>
      <% else %>
        <% Rails.logger.info "No cold symptoms found for current user" %>
        <%= f.hidden_field :cold_symptom_id, value: nil %>
      <% end %>
      
      <%= f.hidden_field :count, value: 0 %>
      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div class="fixed-position">
  <button class="btn btn-mordal" id="openModalButton">
    <i class="fa-solid fa-question fa-xl"></i>
  </button>
</div>

<div class="modal" id="howToUseModal" tabindex="-1" aria-labelledby="howToUseModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="howToUseModalLabel">通知設定</h5>
        <button type="button" class="btn-close" id="closeModalButton" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p class="modal-text text-start">
          このページに表示されているQRコードをカメラで読み込んでください！LINE BOTの友達登録が出来、目標の達成状況を、日曜日に通知します。
        </p>
          <%= image_tag 'QRcode.png', style: 'max-height: 300px; width: auto;' %>
      </div>
    </div>
  </div>
</div>

app/views/goals/edit.html.erb
<% content_for( :title, t('.title'))%>
<div class="container">
  <div class="top-wrapper">
    <div class="col-md-10 col-lg-8 mx-auto">
      <%= render 'form', goal: @goal %>
    </div>
  </div>
</div>

app/views/goals/new.html.erb
<% content_for( :title, t('.title'))%>
<div class="container">
  <div class="top-wrapper">
    <div class="col-md-10 col-lg-8 mx-auto">
      <%= render 'form', goal: @goal %>
    </div>
  </div>
</div>

app/views/goals/show.html.erb
<% content_for( :title, t('.title'))%>
<div class="container">
  <div class="top-wrapper">
    <div class="col-md-10 col-lg-8 mx-auto">
      <div class="box">
        <div class="white-box center">
          <h6>あなたの目標</h6>
          <h4><%= @goal.goal_body %></h4>
          <div id="progress-container-wrapper">
            <div id="progress-container">
              <canvas id="progress-canvas" width="400" height="400"></canvas>
              <div id="progress-text">
                <p><%= @goal.count %>/7</p>
              </div>
              <button id="record-button" data-goal-id="<%= @goal.id %>">達成</button>
            </div>
          </div>
          <div id="comment-container"></div>
        </div>
      </div>
      <div class="box">
        <div class="white-box center">
          <h6>あなたの設定した目標</h6>
          <h3><%= @goal.goal_body %></h3>
          <%= link_to '変更', edit_goal_path(@goal), class: 'btn btn-next' %>
        </div>
      </div>
    </div>
  </div>
</div>